const deck = [
  { value: 1, img: "card-1-b.svg", color: "BLUE" },
  { value: 2, img: "card-2-b.svg", color: "BLUE" },
  { value: 3, img: "card-3-b.svg", color: "BLUE" },
  { value: 4, img: "card-4-b.svg", color: "BLUE" },
  { value: 5, img: "card-5-b.svg", color: "BLUE" },
  { value: 6, img: "card-6-b.svg", color: "BLUE" },
  { value: 7, img: "card-7-b.svg", color: "BLUE" },
  { value: 8, img: "card-8-b.svg", color: "BLUE" },
  { value: 9, img: "card-9-b.svg", color: "BLUE" },
  { value: 1, img: "card-1-y.svg", color: "YELLOW" },
  { value: 2, img: "card-2-y.svg", color: "YELLOW" },
  { value: 3, img: "card-3-y.svg", color: "YELLOW" },
  { value: 4, img: "card-4-y.svg", color: "YELLOW" },
  { value: 5, img: "card-5-y.svg", color: "YELLOW" },
  { value: 6, img: "card-6-y.svg", color: "YELLOW" },
  { value: 7, img: "card-7-y.svg", color: "YELLOW" },
  { value: 8, img: "card-8-y.svg", color: "YELLOW" },
  { value: 9, img: "card-9-y.svg", color: "YELLOW" },
  { value: 1, img: "card-1-r.svg", color: "RED" },
  { value: 2, img: "card-2-r.svg", color: "RED" },
  { value: 3, img: "card-3-r.svg", color: "RED" },
  { value: 4, img: "card-4-r.svg", color: "RED" },
  { value: 5, img: "card-5-r.svg", color: "RED" },
  { value: 6, img: "card-6-r.svg", color: "RED" },
  { value: 7, img: "card-7-r.svg", color: "RED" },
  { value: 8, img: "card-8-r.svg", color: "RED" },
  { value: 9, img: "card-9-r.svg", color: "RED" },
  { value: 1, img: "card-1-g.svg", color: "GREEN" },
  { value: 2, img: "card-2-g.svg", color: "GREEN" },
  { value: 3, img: "card-3-g.svg", color: "GREEN" },
  { value: 4, img: "card-4-g.svg", color: "GREEN" },
  { value: 5, img: "card-5-g.svg", color: "GREEN" },
  { value: 6, img: "card-6-g.svg", color: "GREEN" },
  { value: 7, img: "card-7-g.svg", color: "GREEN" },
  { value: 8, img: "card-8-g.svg", color: "GREEN" },
  { value: 9, img: "card-9-g.svg", color: "GREEN" },
  { value: 0, img: "card-0-b.svg", color: "BLUE" },
  { value: 0, img: "card-0-y.svg", color: "YELLOW" },
  { value: 0, img: "card-0-r.svg", color: "RED" },
  { value: 0, img: "card-0-g.svg", color: "GREEN" },
];

export default deck;
